title: Djahnine Aissam # your name (or website title) here
logo: "/images/DJAHNINE_AISSAM.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hey! I am a Master's degree Student at Sorbonne university Studying Image Processing
  and Computer Vision I'm Passionate about Digital Image Processing, 
  Machine & deep Learning.I am looking Forward to a career in 
  Computer Vision ,I am actively Seeking an internship for 2020 Starting from February.
  Please feel free to reach out for me.  
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/aissamdjahnine/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
