title: Djahnine Aissam # your name (or website title) here
logo: "/images/DJAHNINE_AISSAM_.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hey!
  <br><br>
  <img src="instagram.png?raw=true"/> 
  <br><br>

  <a href="https://www.linkedin.com/in/aissamdjahnine/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
