title: Djahnine Aissam # your name (or website title) here
logo: "/images/DJAHNINE_AISSAM_.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hey!
  
  My strong passion for research in computer vision and its applications in many fields have nurtured from my belief that these areas are rapidly developing
  and offer great scope to one who is confident of producing fruitful work and coming up with creative ideas to make a positive impact, my interest was not
  satisfied by revolving around the outer applications of AI but was constantly demanding to learn more about its inner complexities.

  I have always attempted to make full use of the resources available to me in furthering my knowledge.

  I’m convinced to take a research career, doing a Ph.D. is a stepping-stone to achieving that. It will undoubtedly grant me an opportunity to 
  glance at a deeper level of how to conduct scientific research, from problem definition to understanding how to apply different methodologies
  and make a contribution. If I could find a breakthrough in this field, it will allow me to concretize my goals by making a positive impact
  and adding value to humanity. Regarding my plans after Ph.D. studies, I am aiming for being a chief scientist at one of the giant firms
  of the Healthcare industry making a decent contribution to the scientific community. 
  
  <br><br>
  <br><br>

  <a href="https://www.linkedin.com/in/aissamdjahnine/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
