title: Djahnine Aissam # your name (or website title) here
logo: "/images/DJAHNINE_AISSAM.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hey! I am a Master's degree Student at Sorbonne university My academic credentials
  includes in-progress MSc in computer science with focus on 
  Image processing and computer vision in Sorbonne university (Ex UPMC) in Paris
  which I expect to finish by summer 2020. My curriculum comprised of courses like : 
  Advanced Machine learning and deep learning, Computer Vision, Advanced Image processing,
  Pattern recognition.
  With research and work interests in the application of deep learning techniques in medical diagnosis/prognosis and segmentation.
  ,i am currently working as a Computer Vision and Deep Learning Intern at GE Healthcare on AutoML (Neural Architecure Searh NAS).
  <br><br>
  <a href="https://www.linkedin.com/in/aissamdjahnine/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

