title: Djahnine Aissam # your name (or website title) here
logo: "/images/ad.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hey!
  
  My strong passion for research in computer vision and its applications in many fields have nurtured from my belief that these areas are rapidly developing
  and offer great scope to one who is confident of producing fruitful work and coming up with creative ideas to make a positive impact, my interest was not
  satisfied by revolving around the outer applications of AI but was constantly demanding to learn more about its inner complexities.
  
  <br><br>
  <br><br>

  <a href="https://www.linkedin.com/in/aissamdjahnine/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
